# Generated by Django 5.2.4 on 2025-08-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_userstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='volunteer_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
