# Generated by Django 5.2.4 on 2025-08-15 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_userstats_volunteer_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStats',
        ),
    ]
