# Generated by Django 5.2.4 on 2025-10-01 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergencycall', '0004_stationcatagory_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationcatagory',
            name='icon',
        ),
    ]
