# Generated by Django 5.2.4 on 2025-08-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpneed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helppost',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
