# Generated by Django 5.2.4 on 2025-08-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpneed', '0002_helppost_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helppost',
            name='is_completed',
        ),
    ]
