# Generated by Django 5.2.4 on 2025-08-23 09:12

import django.db.models.deletion
import helpneed.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpneed', '0003_remove_helppost_is_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('on_the_way', 'On The Way'), ('completed', 'Completed')], default='on_the_way', max_length=20)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='helppost',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='helppost',
            name='helpneed_he_created_947257_idx',
        ),
        migrations.RemoveIndex(
            model_name='helppost',
            name='helpneed_he_locatio_94f718_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='helpneed_no_is_read_bc0a21_idx',
        ),
        migrations.RenameField(
            model_name='helppost',
            old_name='description',
            new_name='work_description',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='recipient',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='helppost',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='helppost',
            name='on_the_way_users',
        ),
        migrations.RemoveField(
            model_name='helppost',
            name='post_title',
        ),
        migrations.RemoveField(
            model_name='helppost',
            name='responders',
        ),
        migrations.RemoveField(
            model_name='helppost',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='verb',
        ),
        migrations.AddField(
            model_name='helppost',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='helppost',
            name='responders_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='helppost',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='helppost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='helppost',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='helppost',
            name='location',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='helppost',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='helppost',
            name='post_image',
            field=models.FileField(blank=True, null=True, upload_to='helpposts/', validators=[helpneed.models.image_validator]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='helpneed.helppost'),
        ),
        migrations.AddField(
            model_name='volunteerresponse',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='helpneed.helppost'),
        ),
        migrations.AddField(
            model_name='volunteerresponse',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='volunteerstat',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_stat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='volunteerresponse',
            unique_together={('post', 'volunteer')},
        ),
    ]
