# Generated by Django 5.2.4 on 2025-10-01 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpneed', '0004_volunteerresponse_volunteerstat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helppost',
            old_name='latitude',
            new_name='exactLocation',
        ),
        migrations.RemoveField(
            model_name='helppost',
            name='longitude',
        ),
    ]
