# Generated by Django 5.2.4 on 2025-10-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpneed', '0005_rename_latitude_helppost_exactlocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helppost',
            name='exactLocation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
